# Generated by Django 2.2.7 on 2019-12-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.CharField(max_length=10)),
                ('taskName', models.CharField(max_length=30)),
                ('taskDescription', models.TextField()),
                ('createdDate', models.DateTimeField()),
                ('createdBy', models.CharField(max_length=30)),
                ('assignedTo', models.CharField(max_length=30)),
                ('lastModifiedDate', models.DateTimeField()),
                ('lastModifiedBy', models.CharField(max_length=30)),
                ('remarks', models.TextField()),
                ('status', models.ForeignKey(on_delete='', to='TaskManagement.Status')),
            ],
        ),
    ]
