# Generated by Django 2.2.7 on 2019-12-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0003_auto_20191219_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(default=1, on_delete='', to='TaskManagement.Status'),
        ),
    ]
