# Generated by Django 2.2.7 on 2019-12-20 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0005_drafts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drafts',
        ),
    ]
