# Generated by Django 2.2.7 on 2019-12-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0007_drafts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drafts',
            name='status',
            field=models.ForeignKey(default=4, on_delete='', to='TaskManagement.Status'),
        ),
    ]
